feat: encrypt/decrypt
lewangdev/youtube-drive pull request #9
Opened 2023-02-21 19:10 UTC by gongyisheng

Feature:
Allow optional encrypt/decrypt step while encoding/decoding video and file data.
By default it's not enabled to achieve compatibility with old versions of releases.
I use AES as the crytpo algorithm and follow the code example here: https://pycryptodome.readthedocs.io/en/latest/src/cipher/aes.html

User interface:
There're two flags for this feature:
1. enable_encryption: it's false by default, if you set it to be true, encrypt/decrypt step will be enabled during encoding/decoding
2. encryption_key: it's a user-defined private key, need to be longer than 16 bytes.

User can change these configurations through config file or command line. 
The value passed by command line has a higher priority.

Anything else:
fix two bugs: 
1. encode func, add the case that num_leftover_bytes == 0
2. decode func, data_bytes_retrieved = data_bytes[4:len_of_data+4] , fixing the upperbound. It should be len_of_data+4 or you'll miss the last 4 bytes of data.

2023-02-21 19:11 UTC, gongyisheng commented
@lewangdev Hi Lewang, this PR is ready for review, test passed on my side.

2023-02-23 04:03 UTC, lewangdev requested changes
I tested your branch and it failed. The two issues I mentioned in the code need to be fixed. Thanks for your contribution!

2023-02-23 04:13 UTC, gongyisheng commented on youtube_drive/main.py
> +    encode_parser.add_argument('--key',
I agree it's a typo

2023-02-23 04:13 UTC, gongyisheng commented on youtube_drive/youtube_codec.py
> +import config
Well, import config works on my side, but I'll follow your suggestion. Thanks.

2023-02-23 04:15 UTC, gongyisheng commented
Hi @lewangdev 
Thank you for your reply, I've updated the code. Sorry I only tested `youtube_codec.py` before.

2023-02-23 07:29 UTC, lewangdev requested changes
Your code in youtube_codec.py works well. 
But when I try to use `python -m youtube_drive en -i examples/BesselJ.png examples/test1.mp4` in command line, the program failed again.
```
❯ python -m youtube_drive en -i examples/BesselJ.png examples/test1.mp4
Traceback (most recent call last):
  File "/Users/lewang/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/lewang/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lewang/Workspaces/github.com/lewangdev/youtube-drive/youtube_drive/__main__.py", line 19, in <module>
    youtube_drive.main.main(sys.argv[1:])
  File "/Users/lewang/Workspaces/github.com/lewangdev/youtube-drive/youtube_drive/main.py", line 164, in main
    arguments.handle(arguments)
  File "/Users/lewang/Workspaces/github.com/lewangdev/youtube-drive/youtube_drive/main.py", line 85, in cmd_encode
    youtube_codec.encode(args.i, args.video_filename, args.video_fps, args.encrypt, args.key)
  File "/Users/lewang/Workspaces/github.com/lewangdev/youtube-drive/youtube_drive/youtube_codec.py", line 48, in encode
    num_bytes_per_frame = num_bytes_per_row * num_rows_per_frame
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

here is my lanuch.json in vscode:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "youtube_drive",
            "justMyCode": true,
            "args": ["en", "-i", "examples/BesselJ.png", "examples/test1.mp4"]
        }
    ]
}
```

2023-02-23 08:06 UTC, lewangdev commented on youtube_drive/main.py
> +    youtube_codec.encode(args.i, args.video_filename, args.video_fps, args.encrypt, args.key)
I think we can change the parameter's order of function encode : move `encrypt=ENABLE_ENCRYPTION, key=KEY` before `num_cols_per_frame=64, num_rows_per_frame=36` to fix this problem

2023-02-25 15:13 UTC, merged

2023-02-26 09:35 UTC, lewangdev reviewed
I have changed the code in main.py, code works well now. Merged. 
Thank you for contribution!

2023-02-26 18:32 UTC, gongyisheng commented
Hi @lewangdev 
Sorry I'm enjoying the weekend with my friends. 
Thank you for helping changing the code. Happy to contribute to the project!